# Generated by Django 4.1.3 on 2023-01-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_friend_profile'),
        ('accounts', '0004_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='my_friends', to='core.friend'),
        ),
    ]
